# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4aba62f6113451f0a09cf45a2cfa8f3784579f2c69ceaf9bed319e7418c0ba49286e7ee6b0e8aa63a2d17ddc80fdf4c0f6f5bcc04721b8c140994b034d0efafc

test:
  secret_key_base: 9dfba17fdf0097386a5d323c08c18245e2271b1e350065200de84ec9bc57554e98c634edaa614631c740a179fa474ded59e6123d890d10d589d43bebef383a52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
